name: ci

on: 
  pull_request:
    branches: [ main ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installation dependencies
        run: npm ci

      - name: Test step
        run: npm run test -- --coverage